#!/bin/sh  
unset DISPLAY  
scriptname=$(winepath -w "Hazelcast.iss")
distdir=$(winepath -w "$1")
outputdir=$(winepath -w "$2")
shift 2
echo "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "$scriptname" /O+ "/DDistDir=${distdir}" "/DOutputDir=${outputdir}" "$@"

wine "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "$scriptname" /O+ "/DDistDir=${distdir}" "/DOutputDir=${outputdir}" "$@"
